const School = require("../models/School");
const Student = require("../models/Student");
const jwt = require("jsonwebtoken");

// ==========================
// School Login
// ==========================
const schoolLogin = async (req, res) => {
  const { email, password } = req.body; // Frontend will send email

  try {
    if (!email || !password) {
      return res.status(400).json({ message: "Email and password required" });
    }

    const school = await School.findOne({ loginId: email }); // loginId = email in DB
    if (!school) return res.status(404).json({ message: "School not found" });

    // Direct comparison (plain password, as generated by owner)
    if (password !== school.password) {
      return res.status(400).json({ message: "Invalid credentials" });
    }

    const token = jwt.sign(
      { schoolId: school._id },
      process.env.JWT_SECRET,
      { expiresIn: "1d" }
    );

    res.json({
      success: true,
      message: "Login successful",
      token,
      school
    });
  } catch (err) {
    console.error("❌ Error in schoolLogin:", err);
    res.status(500).json({ message: "Server error" });
  }
};

// ==========================
// Add New Student
// ==========================
const addStudent = async (req, res) => {
  try {
    const schoolId = req.schoolId; // Set by verifySchoolToken
    const { studentName, fatherName, className, dob, mobile, address, other, photo, attachments } = req.body;

    if (!studentName || !fatherName || !className || !dob || !mobile) {
      return res.status(400).json({ success: false, message: "Required fields missing" });
    }

    const newStudent = await Student.create({
      schoolId,
      studentName,
      fatherName,
      className,
      dob,
      mobile,
      address: address || "",
      other: other || "",
      photo: photo || "",
      attachments: attachments || []
    });

    res.status(201).json({ success: true, message: "Student added successfully", student: newStudent });

  } catch (err) {
    console.error("❌ Error in addStudent:", err);
    res.status(500).json({ success: false, message: "Server error" });
  }
};

// ==========================
// List Students
// ==========================
const listStudents = async (req, res) => {
  try {
    const schoolId = req.schoolId;
    const students = await Student.find({ schoolId });
    res.json({ success: true, students });
  } catch (err) {
    console.error("❌ Error in listStudents:", err);
    res.status(500).json({ success: false, message: "Server error" });
  }
};

// ==========================
// Update Student
// ==========================
const updateStudent = async (req, res) => {
  try {
    const { id } = req.params;
    const { studentName, fatherName, className, dob, mobile, address, other, photo, attachments } = req.body;

    const student = await Student.findById(id);
    if (!student) return res.status(404).json({ success: false, message: "Student not found" });

    // Only allow updates by the owning school
    if (student.schoolId.toString() !== req.schoolId) {
      return res.status(403).json({ success: false, message: "Unauthorized" });
    }

    // Update fields
    student.studentName = studentName || student.studentName;
    student.fatherName = fatherName || student.fatherName;
    student.className = className || student.className;
    student.dob = dob || student.dob;
    student.mobile = mobile || student.mobile;
    student.address = address || student.address;
    student.other = other || student.other;
    student.photo = photo || student.photo;
    student.attachments = attachments || student.attachments;

    await student.save();

    res.json({ success: true, message: "Student updated successfully", student });

  } catch (err) {
    console.error("❌ Error in updateStudent:", err);
    res.status(500).json({ success: false, message: "Server error" });
  }
};

module.exports = {
  schoolLogin,
  addStudent,
  listStudents,
  updateStudent
};
